[tool.poetry]
name = "langchain-utils"
version = "0.1.0"
description = ""
authors = ["jeongsk <jeongseok@wantedlab.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "3.11.9"
langchain = "^0.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
